### ISSUE TITLE
Mid-2017 iMacs

### ISSUE THREAD

**Issue by kingpocket** [laurentpertois/BigSur-Compatibility-Checker#2]
I have some mid-2017 iMacs in my fleet that are failing the check.  Their models are 18,1-18,3.  I think because your $MINORMODELVERSION is looking for -ge4, thinking of the 14,4 model minimum.

**Comment by laurentpertois** [comment]
Hi @kingpocket 

Sorry, I missed it, the issue is now fixed. Thanks for that
