### ISSUE TITLE
False "False" Compatibility due to error in logic

### ISSUE THREAD

**Issue by mellamo** [laurentpertois/BigSur-Compatibility-Checker#3]
BLUF: Pre-Sierra Systems need 60GB of free space while Sierra and later need 50GB. The Script currently checks for OSVERSIONMAJOR to be _equal_ to 16. Should be _greater than or equal_ to 16 for the logic to assign the correct required space. [Line 77] Creates a false "False" in compatibility with systems that may be borderline but still able to upgrade.

Background: Minor issue. Had a MacBookPro running 10.13.6 that I knew was compatible but was returning "false." After doing some checking by echoing the values, I determined that the point it was failing was a logic check for the amount of free space needed. It was assigning the number of 60GB needed. It was then that I realized that the if statement was only checking for OSVERSIONMAJOR to be equal to 16 (Meaning only Sierra).

**Comment by laurentpertois** [comment]
Hi @mellamo

good catch, for whatever reason I've thought for a while 50 was only for Catalina so I had a check for equal 19 and then realised it was anything before Sierra and I only changed the number.

Sorry for that and thanks for pointing, I am publishing a new version were -eq is changed to -ge

Have a nice day,
