### ISSUE TITLE
Line 113 on the bash file might have a spacing type-o

### ISSUE THREAD

**Issue by alexanderolvera** [laurentpertois/BigSur-Compatibility-Checker#7]
Not too sure since I don't know much about awk but it's pretty clear that bash is presuming everything under it is an un-encapsulated string. 

Was going to make a pull request for it since the script now works great for my uses in munki but wasn't sure if this is indicative of it's use on jamf or just my poor understanding of awk usage.

**Comment by laurentpertois** [comment]
Hi @LemonArk

Thanks for your comment, can you tell me more about what type you think there is? do you mean like some extra invisible characters taken in the the variable? I checked with "cat -ve" and the output seems clean but I am probably misunderstanding  the issue.

Have a nice day,

**Comment by alexanderolvera** [comment]
Below is the original line. 
`FREESPACE=$(diskutil info / | awk -F'[()]' '/Free Space|Available Space/ {print $2}' | sed -e 's/\ Bytes//')`

The Field separator for AWK does not have a trailing space between the flag and the defined. Again, I don't know much about awk or it's correct syntax but when used as a bash script it is treating it as an un-encapsulated string for the remainder of the file.  

Below is my edited line and now working(at least for me) script in macos. 

`FREESPACE=$(diskutil info / | awk -F '[()]' '/Free Space|Available Space/ {print $2}' | sed -e 's/\ Bytes//')`

Before
![image](https://user-images.githubusercontent.com/53029023/104970585-a1965700-59b1-11eb-98d5-fdaba1a58701.png)
After
![image](https://user-images.githubusercontent.com/53029023/104970593-a8bd6500-59b1-11eb-8504-c5f6b943d10f.png)

Even github is recognizing it as a string. 
![image](https://user-images.githubusercontent.com/53029023/104970639-cb4f7e00-59b1-11eb-974e-b47e6b40941c.png)

I could be totally off here mind you since I am not familiar with AWK and only somewhat with bash but the script for sure is failing on my end to check Mac's properly until after the fix.

**Comment by laurentpertois** [comment]
Ok, I get it. So I've seen and used both syntax with the same results. Here it's how awk interprets the -F option and bash is not involved directly. 

I can change it to add the space, I have no problem with that. But in my tests I see no differences in the result given.

For the sake of safety I'm changing it.

Thanks a lot for your report and the time spent to explain what you see.

Have a nice day,
