### ISSUE TITLE
Wrong Output of Compatibility Check

### ISSUE THREAD

**Issue by IT-Yogi** [laurentpertois/BigSur-Compatibility-Checker#8]
Hey Laurent, 
We noticed that the compatibility status of one of our Macbooks is flagged as "false" even though all requirements are met. 
Also tried several inventory updates, but the wrong status remains.
I am not that familiar with coding but maybe a wrong interpretation of model and OS version which leads to that at least 60 GB are needed? We will try to free some disk space.

![2021-03-18_17-06-39](https://user-images.githubusercontent.com/62701790/111658344-8eb2ce00-880c-11eb-9069-0cf05fb9b76f.png)
![2021-03-18_17-04-26](https://user-images.githubusercontent.com/62701790/111658358-91152800-880c-11eb-807e-e2f9f5711d61.png)

s.

**Comment by IT-Yogi** [comment]
Ok freed some more space and the compatibility check changed to "True".  
So my issue is solved but something went wrong with the interpretation of the requirements. 

![2021-03-18_17-33-00](https://user-images.githubusercontent.com/62701790/111662659-688f2d00-8810-11eb-929e-58f6f5a1c606.jpg)

**Comment by laurentpertois** [comment]
Hi @IT-Yogi,

Sorry for the late response. I just saw your comment.

Not sure what happened but I would have loved to see the output of this command directly on the computer:

`diskutil info / | awk -F '[()]' '/Free Space|Available Space/ {print $2}' | sed -e 's/\ Bytes//'`

This is what I use to check the available space.

APFS can have some weird lags when it comes to free space and real free space, especially when you add Time Machine into the game with local backups.

Let me know if you encounter that issue again and feel free to re-open it.

Have a nice week,
